In [2]:
import numpy as np

In [2]:
arr1 = np.arange(0,11)

In [3]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr1[1]

1

In [8]:
arr1[0]

0

In [10]:
arr1[10]

10

In [11]:
arr1[8]

8

In [12]:
arr1[1:5]

array([1, 2, 3, 4])

this should go up to 1 before 5

In [13]:
arr1[0:5]

array([0, 1, 2, 3, 4])

the above are all getting the value based on the index of an array. 
can also set the values based on index

In [14]:
arr1[0:5]=100

In [15]:
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [3]:
arr1 = np.arange(0,11)

In [4]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

can also slice an array

In [6]:
slice_of_arr1 = arr1[0:6]

In [7]:
slice_of_arr1

array([0, 1, 2, 3, 4, 5])

call on all elements of an array using :

In [8]:
slice_of_arr1[:]=99

In [9]:
slice_of_arr1

array([99, 99, 99, 99, 99, 99])

In [10]:
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

in numpy, data is not copied, it is just a view of the array. only one copy of array in memmory

one has to be specific to make a copy of an array like below. otherwise you're overwriting on your original array.

In [11]:
arr1_copy = arr1.copy()
arr1_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

below is indexing 2-d array

In [14]:
arr_2d= np.array(([5,10,15],[20,25,30],[35,40,45]))

In [15]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

indexing the row

In [16]:
arr_2d[0]
arr_2d[1]

array([20, 25, 30])

In [17]:
arr_2d[0]

array([ 5, 10, 15])

indexing a particular element

In [18]:
arr_2d[1][0]

20

indexing the top left 2 x 2 

In [19]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

indexing the top right 2 x2 

In [20]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

the above in terms of row, ask until the 2nd indexed, in terms of colum ask
for the first indexed and above

fancy indexing

In [22]:
arr2d = np.zeros((10,10)) #this is for the shape (10,10)

In [23]:
arr2d # remember the indexed row is from 0 to 9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
arr_length = arr2d.shape[1]

In [29]:
arr_length # it is a string?

10L

In [30]:
arr2d.shape

(10L, 10L)

In [31]:
arr2d.shape[0]

10L

In [32]:
range(arr_length) # turned into a list of integers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
for i in range(arr_length):
    arr2d[i] = i

the loop above turns every row of arr2d into the index

In [38]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [39]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [40]:
arr2d[[1,3,5,4]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [41]:
arr2d[1,2]

1.0

In [42]:
arr2d[1][2]

1.0