In [4]:
import numpy as np

In [28]:
testarray=  np.arange(3)
testarray


array([0, 1, 2])

In [36]:
print testarray
testarray.shape

[0 1 2]


(3L,)

In [35]:
print testarray.T
testarray.T.shape

[0 1 2]


(3L,)

In [30]:
testarray.reshape((3,1))

array([[0],
       [1],
       [2]])

In [31]:
testarray.reshape((3,1)).shape

(3L, 1L)

In [41]:
print testarray.reshape((3,1)).T
testarray.reshape((3,1)).T.shape

[[0 1 2]]


(1L, 3L)

In [4]:
arr = np.arange(50).reshape((10,5))

In [5]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [6]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

first row becomes the first column

In [7]:
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

3d array

In [5]:
arr3d = np.arange(50).reshape((5,5,2))

In [6]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

transpose a 3d array/matrix

need to specifiy which axises to use

The parameters permute the axes according to the values given.

Check out: http://oz.nthu.edu.tw/~d947207/NVIDIA/copy3D/Matrix_transpose_post.pdf

Under "Transpose on 3D Data" for a more visual explanation of transposing 3d arrays.

In [8]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [9]:
arr = np.array([[1,2,3]])

In [10]:
arr

array([[1, 2, 3]])

In [11]:
arr.shape

(1L, 3L)

swap axes

In [12]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

documentation for the above see http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.swapaxes.html