In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

universal functions are one that applies to each value in the array

take square root

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

binary functions take two arrays

In [8]:
a = np.random.randn(10)
a

array([-0.63964952, -1.28431892, -0.48280347,  0.00813634,  1.20295867,
       -0.81127405,  0.22357519, -0.81595345,  2.21049467, -1.2200547 ])

In [9]:
b=np.random.randn(10)

In [10]:
b

array([-0.7216313 ,  0.61479811,  0.05682415,  1.87800758,  0.45224815,
       -1.67520717,  0.11452567,  0.89664719,  0.2517673 ,  1.15382007])

In [11]:
# binary functions
np.add(a,b)

array([-1.36128082, -0.66952081, -0.42597933,  1.88614392,  1.65520681,
       -2.48648122,  0.33810086,  0.08069374,  2.46226197, -0.06623463])

In [13]:
np.maximum(a,b)

array([-0.63964952,  0.61479811,  0.05682415,  1.87800758,  1.20295867,
       -0.81127405,  0.22357519,  0.89664719,  2.21049467,  1.15382007])

In [14]:
#np.minimum
# documentation for a full list of the universal functions

website = 'https://docs.scipy.org/doc/numpy-1.10.1/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True