In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [3]:
# from numpy
# matrices
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
#concatenate matrices 
# axis = 0 horizontal 
np.concatenate([arr1,arr1],axis =1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)
# vertical union

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# from pandas
# make a series
ser1 = Series([0,1,2],index = ['T','U','V'])
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2 = Series([3,4],index=['X','Y'])
ser2

X    3
Y    4
dtype: int64

In [9]:
#concatenate in pandas
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis =1)
#produce a data frame: keep the index,
# two series become two columns

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
# add hierarchial index to indciate which series source
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4,3),
                    columns = ['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),
                   columns =['Y','Q','X'])


In [13]:
dframe1

X         Y         Z
0  1.721455  0.616411  1.799294
1  0.241100 -0.492740  0.436252
2 -0.455640  0.420655 -0.393037
3  1.332639 -1.393684 -1.068989

In [14]:
dframe2

Y         Q         X
0 -0.404044 -0.647985  0.604121
1  0.423647 -1.144212  0.908057
2  0.063230 -0.427864 -0.349067

In [15]:
pd.concat([dframe1,dframe2]) 
# bind by common columns, rest is filled by nans
# kept the index info on the two data frames

Q         X         Y         Z
0       NaN  1.721455  0.616411  1.799294
1       NaN  0.241100 -0.492740  0.436252
2       NaN -0.455640  0.420655 -0.393037
3       NaN  1.332639 -1.393684 -1.068989
0 -0.647985  0.604121 -0.404044       NaN
1 -1.144212  0.908057  0.423647       NaN
2 -0.427864 -0.349067  0.063230       NaN

In [18]:
# want 'normal' index
pd.concat([dframe1,dframe2],ignore_index = True)

Q         X         Y         Z
0       NaN  1.721455  0.616411  1.799294
1       NaN  0.241100 -0.492740  0.436252
2       NaN -0.455640  0.420655 -0.393037
3       NaN  1.332639 -1.393684 -1.068989
4 -0.647985  0.604121 -0.404044       NaN
5 -1.144212  0.908057  0.423647       NaN
6 -0.427864 -0.349067  0.063230       NaN