In [4]:
import numpy as np

In [5]:
# the above makes typing np equal to numpy

In [6]:
my_list1 = [1,2,3,4]

In [7]:
my_array1 = np.array(my_list1)


In [8]:
my_array1

array([1, 2, 3, 4])

In [9]:
my_list2 = [11,22,33,44]


In [10]:
my_lists = [my_list1,my_list2]

In [11]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [12]:
my_array2= np.array(my_lists)

In [13]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

the above is a multi dimensional array. then what's the dimension?

In [14]:
my_array2.shape

(2L, 4L)

In [15]:
#two rows 

In [16]:
my_array2.dtype

dtype('int32')

data type 

speical case arrays 

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

an array of 1 row, all floating type 0's. 

In [18]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros([3,1])

array([[0.],
       [0.],
       [0.]])

mutli dimensional array =  matrix

In [20]:
np.ones([5,5])



array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.empty(5)

array([0., 0., 0., 0., 0.])

this is the same as creating all zeros.

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

creating an identity matrix. 

In [23]:
np.arange(5)


array([0, 1, 2, 3, 4])

In [24]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])